// ============================================================
// PLACEHOLDER FILE - THIS WILL BE AUTO-GENERATED BY FLUTTERFIRE CLI
// ============================================================
//
// Run this command to generate the real file:
//
//   flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
//
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============================================================
  // PLACEHOLDER VALUES - REPLACE WITH YOUR ACTUAL FIREBASE CONFIG
  // ============================================================
  // After running `flutterfire configure`, this file will be replaced
  // with your actual Firebase configuration.
  // ============================================================

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_IrOWp0JyRGfyKvhcDSC3q-cYOsC2aKc',
    appId: '1:1033859196736:web:a753c4127749c9c45dfca5',
    messagingSenderId: '1033859196736',
    projectId: 'cleanbite-firebase',
    authDomain: 'cleanbite-firebase.firebaseapp.com',
    storageBucket: 'cleanbite-firebase.firebasestorage.app',
    measurementId: 'G-PD9X6RYDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKVLUj2ivakp9qqR_--UwDlw_aWQ3xkc',
    appId: '1:1033859196736:android:a9efd5fbf28fc0c65dfca5',
    messagingSenderId: '1033859196736',
    projectId: 'cleanbite-firebase',
    storageBucket: 'cleanbite-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwYfDyQlFnlaNEASlsk_QUz1uz5GVkmA',
    appId: '1:1033859196736:ios:367cb6f1ba990aa75dfca5',
    messagingSenderId: '1033859196736',
    projectId: 'cleanbite-firebase',
    storageBucket: 'cleanbite-firebase.firebasestorage.app',
    iosClientId: '1033859196736-icdemd6p8q2ndbco7thvt3q9o68eu3eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cursorCleanbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcwYfDyQlFnlaNEASlsk_QUz1uz5GVkmA',
    appId: '1:1033859196736:ios:367cb6f1ba990aa75dfca5',
    messagingSenderId: '1033859196736',
    projectId: 'cleanbite-firebase',
    storageBucket: 'cleanbite-firebase.firebasestorage.app',
    iosClientId: '1033859196736-icdemd6p8q2ndbco7thvt3q9o68eu3eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cursorCleanbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_IrOWp0JyRGfyKvhcDSC3q-cYOsC2aKc',
    appId: '1:1033859196736:web:644bd32a975ece195dfca5',
    messagingSenderId: '1033859196736',
    projectId: 'cleanbite-firebase',
    authDomain: 'cleanbite-firebase.firebaseapp.com',
    storageBucket: 'cleanbite-firebase.firebasestorage.app',
    measurementId: 'G-N2JC4NY7JX',
  );

}